### PR TITLE
Eliminate unnecessary duplication

### PR DESCRIPTION
**Pull request by photodude**
Since the following files are identical to the source; include the rule set and delete the duplicated file.
- add Squiz.WhiteSpace.CastSpacing rule to replace CastSpacingSniff.php
- add Generic.WhiteSpace.DisallowSpaceIndent rule to replace DisallowSpaceIndentSniff.php
- add Squiz.WhiteSpace.MemberVarSpacing rule to replace MemberVarSpacingSniff.php
- add Squiz.WhiteSpace.SemicolonSpacing rule to replace SemicolonSpacingSniff.php
- add PEAR.WhiteSpace.ObjectOperatorIndent rule to replace ObjectOperatorIndentSniff.php
- add Generic.PHP.LowerCaseConstant rule to replace LowerCaseConstantSniff.php
- add PSR2.ControlStructures.ElseIfDeclaration rule as an error rather than a warning to replace ElseIfDeclarationSniff.php

### CODE REVIEW

**Comment by photodude** [comment]
reference issue #104 from @aik099

**Comment by aik099** [comment]
I've updated description of #104 several times, so make sure you've addressed all sniffs.

**Comment by photodude** [comment]
- [x] CastSpacingSniff (removed, see issue #104)
- [x] DisallowSpaceIndentSniff (removed, see issue #104)
- [x] MemberVarSpacingSniff rule (removed)
- [x] SemicolonSpacingSniff (removed, see issue #104)
- [x] ObjectOperatorIndentSniff (removed)
- [x] LowerCaseConstantSniff (removed, see issue #104)
- [ ] ElseIfDeclarationSniff (see issue #104 )
- [ ] SpaceAfterCastSniff (doesn't this conflict with the CastSpacingSniff sniff? see issue #104)
- [ ] ConcatenationSpacingSniff (see issue #104 )
- [ ] SuperfluousWhitespaceSniff (see issue #104 )

For removals related to PHPCS-2 development branch see PR #101

**Comment by aik099** [comment]
Nice catch with these task checkboxes that GitHub have. Would be much easier to track now.

**Comment by photodude** [comment]
@mbabker Do you think it would be better to break this PR up into multiple PRs for each file removal and rule inclusion pair? currently it would be about 7 PRs with consideration for 3 others.

**Comment by mbabker** [comment]
Truthfully, it doesn't matter much to me.  As long as I (or someone) can make sense of it all when sitting down to go through it; if it's clearly explained somewhere I'm not too picky about it being one PR.

**Comment by photodude** [comment]
@mbabker My thought was it might be easier for you (or someone) to sit down and look at each one individually and approve one here and there; rather than the larger time commitment to review as one big PR.

But taking your advice for this to be "clearly explained somewhere," I have updated the PR description to cover the intent and current inclusions of this PR.

**Comment by photodude** [comment]
@mbabker shall we finish this 1.x PR or close in favor of "leaving the 1.x structure in a "minimal maintenance" type of state." ?

**Comment by mbabker** [comment]
Ya, let's just leave things alone.  The whole "if it ain't broke" thing.  Better for us to put our code focus on the 2.x ruleset at this point.

**Pull request closed without merging**
