### PR TITLE
Add SCSS Coding Standards

### PR DESCRIPTION
**Pull request by C-Lodder**
This PR adds the coding standards for SCSS, in addition to some minor tweaks for CSS

### CODE REVIEW

**Comment by photodude** [comment]
Should we also list LESS here as well?

**Comment by C-Lodder** [comment]
I can't see how we can add coding standards for LESS as the J3.x files are absolutely diabolical.

**Comment by photodude** [comment]
According to how I read it the existing standards suggest the LESS files should have followed the CSS standards and the nesting like SCSS

**Comment by zero-24** [comment]
I'm not sure here. The coding standards with scss are only valid for 4.0 for 3.x we still have LESS as default so we can apply this change before 4.0 is live :smile:

**Comment by photodude** [comment]
Considering LESS will be alive and supported in the 3.x branch for like the next 2 years we should include that in the standard even if the files are not actually compliant with the expected code style.

**Comment by C-Lodder** [comment]
Once the LESS standards have been applied, someone will then have to apply those standards. Whoever does that....well all I can say is good luck and enjoy.

**Comment by mbabker** [comment]
@C-Lodder Would you be able to redo this PR against the master branch?  We've dropped the `gh-pages` branch and using GitHub pages for the manual in favor of showing it through a component on https://developer.joomla.org.

**Comment by C-Lodder** [comment]
sure, will do tomorrow

**Comment by C-Lodder** [comment]
@mbabker done: https://github.com/joomla/coding-standards/pull/155

**Pull request closed without merging**
