### PR TITLE
Don't allow package tags in namespaced files

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull request for https://github.com/joomla/joomla-cms/issues/26395.

@mbabker please review. Should this be applied to all namespaced files or only to namespaced classes? We don't have the former in the CMS so not sure how to handle those.

### CODE REVIEW

**Comment by wilsonge** [comment]
I'd stick with namespaced classes.

**Comment by SharkyKZ** [comment]
I somehow totally screwed up this code, nothing makes sense 🤦‍♂

**Comment by SharkyKZ** [comment]
Should be good now.

**Comment by wilsonge** [comment]
Let's give it a spin :)

**Comment by SharkyKZ** [comment]
Thanks.

**Pull request merged**
