### PR TITLE
Add deprecated classes and functions check

### PR DESCRIPTION
**Pull request by Ruud68**
My first PR for reporting deprecated classes and codes.

### CODE REVIEW

**Comment by mbabker** [comment]
We can't actually add these sniffs to this repo.  This repo has the generic PHPCS ruleset for all Joomla projects, and these sniffs are specific to the CMS.  The mailing list thread on this is why I opened https://github.com/joomla/joomla-cms/issues/19395 to get the CMS' extended ruleset moved to a separate repo, because ultimately that is where this needs to be merged.

**Comment by Ruud68** [comment]
Okay, so it ends :)
missed that RFC (https://github.com/joomla/joomla-cms/issues/19395).
How do I keep track of when that RFC is accepted / implemented so I can do a PR there?

**Comment by mbabker** [comment]
Subscribe to notifications on that issue and you'll be set.

**Comment by nibra** [comment]
Wouldn't it make sense to have a collection of J! related sniffs in the `Joomla/` directory and reference them as needed in separate rulesets like `Joomla-Generic` and `Joomla-CMS`? That would promote segregation of style definition and code base and allow to use those sniffs fx. in JED.

**Comment by mbabker** [comment]
Well, it depends how we want to manage things.  Do we want application specific rulesets to live in this repository or should there be some form of inheritance/hierarchy for that (i.e. this `coding-standards` repo for the base ruleset and `cms-coding-standards` as an extension of this repo)?  Personally, I'd treat it as two separate rulesets where one makes use of the other (same as we do now making use of sniffs defined in PEAR or Squiz standards).

**Comment by nibra** [comment]
Having separate rulesets does not require separate repositories, as far as I understand (I might be corrected, though). We obviously need separate sets (with a common base), and inheritance/hierarchy makes absolutely sense. But I don't see that we need separate repositories for that.

**Pull request closed without merging**
