### PR TITLE
Use Bootstrap3 and Visual Enhancement

### PR DESCRIPTION
**Pull request by asika32764**
- Add Bootstrap3 Adapter to make old code with BS3 style.
- Some visual update to fit Joomla blue style
- Update css to make style look like Github

http://about.asika.tw/sms-joomla-coding-standards/

### CODE REVIEW

**Comment by mbabker** [comment]
9 months of no activity.  Any interest in following up or is this something we can close for lack of interest (along with my parent item #52)?

**Comment by photodude** [comment]
@mbabker What is needed to get this PR merged?

**Comment by Hutchy68** [comment]
Me 😀

I've now built a few static sites with docpad and it's all in how you run the command line to build with appropriate switch variables. I can't get to it until the following weekend.

**Comment by photodude** [comment]
Is this needed considering #141 ?

**Comment by mbabker** [comment]
Nope.  If I ever figure out what bug it was Brian was trying to get addressed blocking the completion of integrating everything into https://developer.joomla.org then everything will be hosted natively through that site.

**Pull request closed without merging**
