### PR TITLE
.md to .html

### PR DESCRIPTION
**Pull request by Paladin**
fixes the website, breaks the link in GitHub. Your call for which one you want to have broken.

### CODE REVIEW

**Comment by photodude** [comment]
From the manual website https://developer.joomla.org/coding-standards.html I click on the link in the text that is modified in this PR I get the following url with a 404 https://developer.joomla.org/appendices/analysis.md

But if I click on the left-hand menu I get the correct URL https://developer.joomla.org/coding-standards/analysis.html

the github links are correct

I think this is an issue with the parser that creates the page. @mbabker thoughts?

**Comment by mbabker** [comment]
One of these days I'm going to have to get a subscription plan for JMarkdown, get the site updated to the current version of the component, and see if there's a way to hook it and process the file somehow to fix the links.

**Comment by photodude** [comment]
I propose closing this PR and opening an issue indicating the broken link and the cause related to JMarkdown parsing.

**Comment by mbabker** [comment]
I thought we had an issue open somewhere, but looking in https://github.com/joomla/joomla-websites/issues and https://github.com/joomla/developer.joomla.org/issues I guess not.

**Comment by Paladin** [comment]
Fine by me. Like I said, it's your call. I just promised to submit the PR, didn't promise to insist it get accepted.

**Pull request closed without merging**
