### PR TITLE
Merge manual and IDE changes from master into phpcs-2

### PR DESCRIPTION
**Pull request by photodude**
brings in the manual and IDE changes in preparation for moving phpcs-2 to master

### CODE REVIEW

**Comment by photodude** [comment]
@wilsonge did I do the merge from master to phpcs-2 correct? It seemed not so bad with just the 6 issues to fix.

**Comment by wilsonge** [comment]
I *think* it's ok having looked at the diff between your branch and MASTER. But if i merge this and it's wrong we're in a world of pain. @mbabker can you give a second review to be safe please

**Comment by mbabker** [comment]
Merge the current master branch into the 1.x branch then if you're comfortable with this you can merge phpcs-2 into master and delete it.  We'll still have the 1.x branch to pick from if need be.

**Comment by wilsonge** [comment]
Done as you suggested. I've merged Walt's branch into master (and kept the current travis file which conflicted). 

https://github.com/joomla/coding-standards/commit/a74520de057fca61f66a49478dfc00d90deee506

We can leave the phpcs-2 branch here whilst we make sure it looks good. But let's assume all new PHPCS 2 PR's should be against master NOT the PHPCS-2 branch

**Comment by photodude** [comment]
Looks like a good solution. Thanks @mbabker and @wilsonge

**Pull request closed without merging**
