### PR TITLE
[PHPCS2] add note to message adjustments Note: the autofixer will convert spaces to tabs

### PR DESCRIPTION
**Pull request by photodude**
This covers the pear rules with adjusted messages to report spaces as tabs. This is a better solution without needing custom sniffs.

### CODE REVIEW

**Comment by wilsonge** [comment]
Does `PEAR.ControlStructures.MultiLineCondition.Alignment` and `PEAR.WhiteSpace.ObjectOperatorIndent.Incorrect` not require a similar modification?

**Comment by photodude** [comment]
Probably, will need to do the same modification to all indent messages that report spaces.

`Squiz.WhiteSpace.ScopeClosingBrace.Indent` is another to adjust

**Comment by wilsonge** [comment]
I mean i don't *like* this. It's just custom sniffs for all of this is just worse.... :/

**Comment by photodude** [comment]
It's the quickest, cleanest and has the least overhead for us in the long term. 

The other option to avoid all of this would be to try and contribute tab reporting for these sniffs to PHPCS and hope they will accept it. For example `Generic.WhiteSpace.ScopeIndent.Incorrect` can report as spaces or as tabs if a flag is set in the ruleset <property name="tabIndent" value="true"/>.

**Comment by wilsonge** [comment]
What do you think the likelihood of that being accepted is?

**Comment by photodude** [comment]
one a side note: I have on old PR open with PHPCS that would eliminate one of our custom sniffs, but it needs some work to be accepted. https://github.com/squizlabs/PHP_CodeSniffer/pull/972

**Comment by photodude** [comment]
Seems like they might accept something like tabIndent as they have set up sniff with that. (but I do know they preference spaces)

**Comment by wilsonge** [comment]
Honestly I'm happy to accept this now as long as we give the PR a go. But if we are going to do this as a temporary measure now let's get those rules that me and you have mentioned that also need custom messages implemented too :)

**Comment by photodude** [comment]
I'll see if I can get to those additional messages a little later tonight. (I'm technically tied up with stuff for the next 2 hours)

**Comment by wilsonge** [comment]
No rush :)

**Comment by wilsonge** [comment]
OK. Merged. Let's work on trying to get a better fix to the sniff for this upstream though :)

**Comment by photodude** [comment]
Agreed, That seems like the best plan.

**Comment by wilsonge** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/pull/1362

**Pull request merged**
