### PR TITLE
Stage 2 - remove gh-pages

### PR DESCRIPTION
**Pull request by brianteeman**
This is stage 2 of the move from gh-pages.

Please dont merge until after step 1 has been merged AND until it has been added to dev.j.o

### CODE REVIEW

**Comment by mbabker** [comment]
Just say when...

**Comment by brianteeman** [comment]
Will do in a few hours

**Comment by brianteeman** [comment]
Hit a bug in the component with alias generation so it wont be today

**Comment by photodude** [comment]
Should also deal with the open PR's that affect the GH-pages see PR #61, PR #78, PR #89, and PR #91

**Comment by mbabker** [comment]
Ready for review - https://developer.joomla.org/coding-standards.html

**Comment by zero-24** [comment]
Looks great. :+1:  Do we have a change for syntax higlyting?

syntax

**Comment by mbabker** [comment]
GitHub's pages have syntax highlighting integrated into its CSS.  We'll need to add a CSS library for it to do the same.

**Comment by mbabker** [comment]
All we might need is https://github.com/joomla/jissues/blob/master/www/media/css/code.css which we use on the issue tracker for our markdown demo pages - https://issues.joomla.org/markdown (code tab)

**Comment by mbabker** [comment]
Actually, that CSS is based on an old version of GitHub's markdown parser, it isn't really good anymore.

I did test out https://github.com/primer/github-syntax-light quickly and it does the job adequately.  I can add loading that to our layout override later on.

**Comment by photodude** [comment]
Page one

```
Contributing to this manual

If you want to contribute and improve this manual, you can find the source files at https://github.com/joomla/coding-standards/tree/gh-pages.
```

I'm assuming this section needs to be updated

Other than the syntax highlighting, it looks fairly good. We also have a new PR to include covering SCSS See #146

**Comment by zero-24** [comment]
About the section Contributing to this manual i have noted this in the other issue too. But atm this is only a 1v1 copy of the content :)

**Comment by mbabker** [comment]
I've added the CSS for the syntax highlighting.  Content updates can be handled as pull requests to the master branch.

**Pull request merged**
