### PR TITLE
Reorganising Package for use with Composer and PHP CodeSniffer 2

### PR DESCRIPTION
**Pull request by nibra**
This PR contains a complete overhaul of the coding standards package.

Changes:
- Moved code to `src/Joomla` for use with Composer
- Changed test structure to allow test of not only own sniffs, but _all_ rules of the standard
- Added tests for all sniffs referenced in `ruleset.xml`
- Added auto-registering of the Joomla Coding Standard to PHP CodeSniffer
- Completely covers PR #109 
- Added RoboFile for simple test execution

Unfortunately, the files list treats moved files as deletions/additions.

### CODE REVIEW

**Comment by photodude** [comment]
@nibra Can you review and fix the conflicts?

**Comment by nibra** [comment]
@photodude Done.

**Comment by photodude** [comment]
Thanks @nibra 

Am I reading the commit history right and there is stuff about "installed WordPress standard"?
If that's right, I'm doubtful that "WordPress standards" would be allowed to be included in the Joomla! standard.

**Comment by nibra** [comment]
I know developers, that write code for both Joomla and Wordpress, so the GreenCape package provides both. Of course it will not be referenced in Joomla's phpcs.xml.

**Comment by photodude** [comment]
Including the Wordpress stuff in your GreenCape package is all well and good. I personally don't see that as appropriate source code inclusion for the Joomla! coding standards; whether they are referenced in the ruleset.xml file or not.

I'm not a maintainer, just a contributor so I don't have a say on what gets merged. But I wouldn't approve of such an inclusion, as such I won't test this PR as an alternative to PR #109 while the Wordpress information is included in the source code.

**Comment by nibra** [comment]
Just checked: The Wordpress rules are **not** included in this PR. However, some file changes that were made in the 'big' package `GreenCape/coding-standards` when adding the Wordpress standard, also affected files needed here. If you look at the files contained in the commit in question, you'll not find any WP related stuff. I'm sorry that I didn't remember that already last week.

**Comment by photodude** [comment]
What about this commit that says, "[added wordpress rules](https://github.com/GreenCape/coding-standards/commit/a54a081630d47cf972ab23b12a12aa273e9f3dc6)"?

**Comment by nibra** [comment]
As I said, "some file changes that were made in the 'big' package GreenCape/coding-standards when adding the Wordpress standard, also affected files needed here". That's why some files from that commit made it over here.

**Comment by photodude** [comment]
Like the [Wordpress sniff](https://github.com/GreenCape/coding-standards/blob/a54a081630d47cf972ab23b12a12aa273e9f3dc6/src/WordPress/Sniff.php)

**Comment by photodude** [comment]
@nibra I had some time over the weekend to look over the files vs the commits. I can see that the commit history says one thing but the final state of the files say another, just as you had indicated.

Might be a good idea to do a "squash" your commits with something like `git reset soft HEAD~x` (where x is the number of commits from current back to the source head) and provide a summary of what was in all of the commits. but as I mentioned before: I'm not a maintainer, just a contributor so I don't have a say on what gets merged or how or even if the commits should or shouldn't be condensed.

In either case, I'm hoping to put some more work into #109 soon in an attempt to solve some of the outstanding issues (there is a checklist somewhere in that PR of things to address) which are holding up the PR. There is some desire floating about to have the CMS use PHPCS 2 around 3.5.1 or at the latest before 3.6.

**Comment by photodude** [comment]
@mbabker I believe this can be closed as it's going in a different direction and does not include everything that's in [the phpcs-2 branch](https://github.com/joomla/coding-standards/tree/phpcs-2)

**Pull request closed without merging**
